name: Gatsby Publish

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '12.14.1'
          registry-url: 'https://registry.npmjs.org'
      - run: yarn install --production
      - run: node ./create-env.js --gatsby-disqus-name="${{ secrets.LOWTRIP_REGISTRY_PASSWORD }}"
      - uses: enriikke/gatsby-gh-pages-action@v2
        with:
          access-token: ${{ secrets.ACCESS_TOKEN }}
          deploy-branch: gh-pages
          gatsby-args: --prefix-paths